service:
  name: product-page-svc
  port: 9080

productionDeployment:
  replicaCount: 2
  weight: 100
  image:
    repository: joelwenzel/natours
    tag: 1.0.4
    pullPolicy: IfNotPresent


canaryDeployment:
  replicaCount: 0
  weight: 0
  image:
    repository: joelwenzel/natours
    tag: 1.0.6
    pullPolicy: IfNotPresent



